spring.application.name=Smart_Grocery

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/smart_pantry
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.mvc.throw-exception-if-no-handler-found=false
spring.thymeleaf.cache=false
spring.web.resources.cache.period=0
spring.web.resources.chain.cache=false

app.jwt.secret=mhexuglpj37XzKeSrRIInE1XKANYHRF1smgqp0ZBTBGMpTlnHxNdbSfgDiaRYW+DXBsmBHW0ua4+jw7HkZkRpg==
app.jwt.expiration-ms=86400000